### ISSUE TITLE
current_time issue

### ISSUE THREAD

**Issue by SeekPoint** [lemonhu/finance-qa-spider#1]
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE IF NOT EXISTS `shse_qa`(
    ->     -> `current_time` TIMESTAMP NOT NULL,
    ->     -> `user_name` VARCHAR(100) NOT NULL,
    ->     -> `company_name` VARCHAR(100) NOT NULL,
    ->     -> `company_id` int(20) NOT NULL,
    ->     -> `question_time` VARCHAR(100) NOT NULL,
    ->     -> `question_content` text NOT NULL,
    ->     -> `answer_time` VARCHAR(100),
    ->     -> `answer_content` text
    ->     -> )ENGINE=InnoDB DEFAULT CHARSET=utf8;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-> `current_time` TIMESTAMP NOT NULL,
    -> `user_name` VARCHAR(100) NOT NULL,
' at line 2
mysql>

**Comment by SeekPoint** [comment]
[Failure instance: Traceback: <class 'MySQLdb._exceptions.IntegrityError'>: (1364, "Field 'current_time' doesn't have a default value")
c:\users\andyy\appdata\local\programs\python\python37\lib\threading.py:917:_bootstrap_inner
c:\users\andyy\appdata\local\programs\python\python37\lib\threading.py:865:run

**Comment by lemonhu** [comment]
Thank you for reporting. There is no problem in creating the data table by executing the following command. It should be noted that the command does not contain an arrow.

> CREATE TABLE IF NOT EXISTS \`shse_qa\`(
    \`current_time\` TIMESTAMP NOT NULL,
    \`user_name\` VARCHAR(100) NOT NULL,
    \`company_name\` VARCHAR(100) NOT NULL,
    \`company_id\` int(20) NOT NULL,
    \`question_time\` VARCHAR(100) NOT NULL,
    \`question_content\` text NOT NULL,
    \`answer_time\` VARCHAR(100),
    \`answer_content\` text
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by SeekPoint** [comment]
`current_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP

can be compatible with the mysql8.0.15
