### ISSUE TITLE
似乎只能爬取sns的，另外几个呢

### ISSUE THREAD

**Issue by SeekPoint** [lemonhu/finance-qa-spider#2]
深交所官方平台的问答系统
http://irm.cninfo.com.cn/szse/index.html　　

全景网投资者关系互动平台
http://rs.p5w.net/index/company/showQuestionPage.shtml　　

新浪股吧
http://guba.sina.com.cn/?s=channel&chi

**Comment by lemonhu** [comment]
谢谢关注，个人研究与时间原因，该repo已经停止维护了，代码仅供参考哈~

**Comment by SeekPoint** [comment]
太小气了吧

**Comment by lemonhu** [comment]
😄这个是两年前的repo了，有段时间不做爬虫这块内容了，还请理解，估计上述网站网页有改动，需要你重新适配解析，代码主体框架与处理流程还是可以供你参考，修改应该不会困难的。
